package gd.app.musicplayer.playback.command

object PlaybackServiceActions {
    const val ACTION_EXIT = "opraton_action_exit"
    const val ACTION_CHANGE_MODE = "opraton_action_change_mode"
    const val ACTION_MODE_RANDOM = "ACTION_MODE_RANDOM"
    const val ACTION_CHANGE_MUSIC_BY_INDEX = "music_action_change_music2"
    const val ACTION_DESK_LRC_LOCK = "ACTION_DESK_LRC_LOCK"

    const val ACTION_PLAY_FROM_QUEUE = "gd.app.musicplayer.action.PLAY_FROM_QUEUE"
    const val ACTION_ENQUEUE = "gd.app.musicplayer.action.ENQUEUE"
    const val ACTION_PLAY_NEXT = "gd.app.musicplayer.action.PLAY_NEXT"
    const val ACTION_REPLACE_QUEUE = "gd.app.musicplayer.action.REPLACE_QUEUE"
    const val ACTION_TOGGLE_PLAY_PAUSE = "gd.app.musicplayer.action.TOGGLE_PLAY_PAUSE"
    const val ACTION_PLAY = "gd.app.musicplayer.action.PLAY"
    const val ACTION_PAUSE = "gd.app.musicplayer.action.PAUSE"
    const val ACTION_NEXT = "music_action_next"
    const val ACTION_PREVIOUS = "music_action_previous"
    const val ACTION_SEEK_TO = "gd.app.musicplayer.action.SEEK_TO"
    const val ACTION_CLEAR_QUEUE = "gd.app.musicplayer.action.CLEAR_QUEUE"
    const val ACTION_REMOVE_QUEUE_ITEM = "gd.app.musicplayer.action.REMOVE_QUEUE_ITEM"
    const val ACTION_MOVE_QUEUE_ITEM = "gd.app.musicplayer.action.MOVE_QUEUE_ITEM"
    const val ACTION_UPDATE_TRACK_METADATA = "gd.app.musicplayer.action.UPDATE_TRACK_METADATA"
    const val ACTION_UPDATE_TRACKS_METADATA = "gd.app.musicplayer.action.UPDATE_TRACKS_METADATA"
    const val ACTION_STOP = "music_action_stop"
    const val ACTION_QUIT = "gd.app.musicplayer.action.QUIT"
    const val ACTION_TOGGLE_FAVORITE = "gd.app.musicplayer.action.TOGGLE_FAVORITE"
    const val ACTION_SET_STOP_AFTER_CURRENT_TRACK = "gd.app.musicplayer.action.SET_STOP_AFTER_CURRENT_TRACK"
    const val ACTION_APPLY_AUDIO_EFFECTS = "gd.app.musicplayer.action.APPLY_AUDIO_EFFECTS"
    const val ACTION_APPLY_PLAYBACK_TUNING = "gd.app.musicplayer.action.APPLY_PLAYBACK_TUNING"
    const val ACTION_REFRESH_NOTIFICATION_STYLE = "gd.app.musicplayer.action.REFRESH_NOTIFICATION_STYLE"
    const val ACTION_RESTART_CURRENT = "gd.app.musicplayer.action.RESTART_CURRENT"
    const val ACTION_CUSTOM_FAVORITE = "gd.app.musicplayer.action.FAVORITE"
    const val ACTION_CUSTOM_UNFAVORITE = "gd.app.musicplayer.action.UNFAVORITE"
    const val ACTION_CUSTOM_STOP = "gd.app.musicplayer.action.STOP_CUSTOM"
}
