package gd.app.musicplayer.ui.feature.setting

data class SettingsUiState(
    val useTenBand: Boolean = false,
    val useTenBandAvailable: Boolean = true,
    val showHiddenFolders: Boolean = true,
    val darkModeEnabled: Boolean = false,
    val showForwardBackward: Boolean = false,
    val forwardBackwardSeconds: Int = 15,
    val queueForSearchingMode: Int = 0,
    val queueForSearchingLabel: String = "",
    val bluetoothLyricEnabled: Boolean = true,
    val shakeEnabled: Boolean = false,
    val shakeLevel: Float = 0.5f,
    val shakeLevelLabel: String = "",
    val swipeChangeSongsEnabled: Boolean = true,
    val simultaneousPlayEnabled: Boolean = false,
    val volumeFadeEnabled: Boolean = false,
    val gaplessPlaybackEnabled: Boolean = false,
    val crossFadeEnabled: Boolean = false,
    val fadeDurationSeconds: Int = 6,
    val trackClickOperationEnabled: Boolean = false,
    val replaySongEnabled: Boolean = false,
    val replayGainMode: Int = 0,
    val replayGainModeLabel: String = "",
    val replayGainPreampWithTag: Float = 0f,
    val replayGainPreampWithoutTag: Float = 0f,
    val replayGainPreampLabel: String = "",
    val clickAddQueueEnabled: Boolean = false,
    val playlistAddPosition: Int = 0,
    val playlistAddPositionLabel: String = "",
    val smartPlaylistSelectionIndex: Int = 0,
    val smartPlaylistCustomLimit: Int = -1,
    val playlistTrackLimitLabel: String = "",
    val notificationBarEnabled: Boolean = false,
    val notificationPermissionGranted: Boolean = true,
    val oldNotificationEnabled: Boolean = false,
    val colorNotificationEnabled: Boolean = true,
    val colorNotificationEnabledAvailable: Boolean = true,
    val lockScreenEnabled: Boolean = true,
    val lockBackgroundMode: Int = 1,
    val lockBackgroundLabel: String = "",
    val headsetInPlayEnabled: Boolean = false,
    val headsetOutStopEnabled: Boolean = true,
    val bluetoothAutoStartEnabled: Boolean = false,
    val bluetoothAutoStopEnabled: Boolean = true,
    val bluetoothPermissionGranted: Boolean = true,
    val headsetControlAllowed: Boolean = true
)

